spring.application.name=service
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:./data/movies.db
spring.datasource.driver-class-name=org.sqlite.JDBC
